import type { Metadata } from "next";
import { Cairo, Roboto } from "next/font/google"; // ✅ ضفنا Cairo و Roboto
import "./globals.css";
import SplashCursor from "@/components/ui/SplashCursor";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
  weight: ["200","300","400","500","600","700","800","900"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300","400","500","700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ✅ Cairo + Roboto */}
      <body className={`${cairo.variable} ${roboto.variable} antialiased`}>
        <SplashCursor />
        {children}
      </body>
    </html>
  );
}
